### ISSUE TITLE
关于使用gradle插件引入高德地图sdk的问题

### ISSUE THREAD

**Issue by baoyachi** [amap-demo/android-path-record#1]
哥们，请问新版的高德地图是使用gradle引入高德地图sdk吗？不再使用提供jar包的形式吗❓ 

😃 😃 😃

**Comment by mayan0** [comment]
两种形式都有，jar包可以去官网下载
http://lbs.amap.com/api/android-sdk/download

**Comment by baoyachi** [comment]
👍  好久的issue，赞一个
